baseURL = 'https://tech.epsilondelta.ai/'
languageCode = 'ko-KR'
title = '엡실론델타 테크블로그'
theme = 'epsilondelta'

[params]
  titleStrong = '엡실론델타'
  titleLight = '테크블로그'
  logo = '/logo.jpg'
  featuredTags = ['ai', 'backend', 'frontend', 'devops', 'security', 'aws', 'gcp', 'azure', 'kubernetes', 'docker', 'serverless', 'microservices', 'graphql', 'rest', 'websockets', 'http2', 'grpc', 'oauth2', 'jwt', 'openapi', 'swagger']

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
