baseURL = 'https://tech.epsilondelta.ai/'
languageCode = 'ko-KR'
title = '엡실론델타 테크블로그'
theme = 'epsilondelta'
enableRobotsTXT = true

[params]
  description = '엡실론델타 테크블로그입니다.' # for meta og tag
  images = ['logo.jpg'] # for meta og tag
  title = '엡실론델타 테크블로그' # for meta og tag
  # [params.social]
  #   facebook_admin = 'jsmith' # for meta og tag
  titleStrong = '엡실론델타'
  titleLight = '테크블로그'
  logo = '/logo.jpg'
  featuredTags = [] # 페이지 상단에 강조하고 싶은 태그들을 나열합니다.

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[taxonomies]
  tag = 'tags'
  author = 'authors'
  post = 'posts'
  series = 'series'

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 10

[[menus.main]]
name = 'Authors'
pageRef = '/authors'
weight = 20

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

# [services]
#   [services.disqus]
#     shortname = 'your-disqus-shortname'
#   [services.googleAnalytics]
#     id = 'G-MEASUREMENT_ID'
