baseURL = 'https://tech.epsilondelta.ai/'
languageCode = 'ko-KR'
title = '엡실론델타 테크블로그'
theme = 'epsilondelta'
enableRobotsTXT = true

[markup]
  _merge = 'deep'

[params]
  _merge = 'deep'
  description = '엡실론델타 테크블로그입니다.' # for meta og tag
  images = ['epsilondelta_logo_v3.jpg'] # for meta og tag
  title = '엡실론델타 테크블로그' # for meta og tag
  # [params.social]
  #   facebook_admin = 'jsmith' # for meta og tag
  #   twitter = 'GoHugoIO' # for meta twitter tag
  titleStrong = '엡실론델타'
  titleLight = '테크블로그'
  logo = '/epsilondelta_symbol_v3.png'
  featuredTags = [] # 페이지 상단에 강조하고 싶은 태그들을 나열합니다.
  [params.giscus]
    enabled = false
    repo = 'Epsilondelta-ai/tech.epsilondelta.ai'
    repoId = ''
    category = 'General'
    categoryId = ''
    theme = 'light'

# [services]
#   [services.disqus]
#     shortname = 'your-disqus-shortname'
#   [services.googleAnalytics]
#     id = 'G-MEASUREMENT_ID'

[pagination]
  _merge = 'deep'

[taxonomies]
  _merge = 'deep'

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 10

[[menus.main]]
name = 'Authors'
pageRef = '/authors'
weight = 20

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  _merge = 'deep'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
